require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 6
  MaxOptionalParameters: 5
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
